version: '3.8'

services:
  db:
    image: postgres:15
    container_name: unitakas_db
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: supergizlisifre123
      POSTGRES_DB: unitakas
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  n8n:
    image: docker.n8n.io/n8nio/n8n
    container_name: unitakas_n8n
    ports:
      - "5678:5678"
    environment:
      - N8N_HOST=localhost
      - N8N_PORT=5678
      - N8N_PROTOCOL=http
      - NODE_ENV=production
    volumes:
      - n8n_data:/home/node/.n8n
    depends_on:
      - db

volumes:
  postgres_data:
  n8n_data:

